/**:
  ros__parameters:
    basic:
      map_frame: "map"                              # 发布坐标系
      map_match_hz: 2.0                             # 地图匹配频率
      #saved_map: "/home/jw-zkl/ros_ws/map/result_bag"   # 地图包路径，必须使用绝对路径
      visualize_voxel_size: 0.3                     # 可视化时的体素降采样分辨率

    keyframe:
      keyframe_threshold: 1.5                       # 关键帧距离阈值，单位 [米]，每移动这么远生成一帧关键帧
      num_submap_keyframes: 5                       # 构建子地图时使用的关键帧数量，范围通常为 [closest-this, closest+this]（如果存在）

    match:
      quatro_nano_gicp_voxel_resolution: 0.1        # Quatro 和 Nano-GICP 匹配时使用的体素分辨率
      scancontext_max_correspondence_distance: 35.0 # ScanContext 找到候选后，用于进一步筛选候选帧的最大距离阈值

    nano_gicp:                                      # 以下参数来自 Nano-GICP 官方仓库（Direct LiDAR Odometry）
      thread_number: 0                              # 线程数，若为 0 则使用 CPU 最大核心数
      icp_score_threshold: 1.5                      # ICP 匹配分数阈值，越小表示匹配越准确，用于地图-扫描匹配结果判定
      correspondences_number: 15                    # 每个点用于建立匹配关系的对应点数量
      max_correspondence_distance: 35.0             # 最大对应点距离，同时也可用于候选帧筛选
      max_iter: 32                                  # ICP 最大迭代次数
      transformation_epsilon: 0.01                  # 两次迭代间变换量收敛阈值
      euclidean_fitness_epsilon: 0.01               # 欧式适应度收敛阈值
      ransac:
        max_iter: 5                                 # RANSAC 最大迭代次数
        outlier_rejection_threshold: 1.0            # RANSAC 外点剔除阈值

    quatro:                                         # 以下参数来自 Quatro 官方仓库,Quatro需要雷达数据稠密
      enable: true                                  # 是否启用 Quatro；若为 false，则退化为 FAST-LIO-SAM-N（仅使用 Nano-GICP）
      optimize_matching: true                       # 是否启用优化后的特征匹配策略
      distance_threshold: 30.0                      # 在优化匹配模式下，仅使用该半径范围内的对应关系，单位 [米]
      max_correspondences: 350                      # 优化匹配时允许使用的最大对应点数量
      fpfh_normal_radius: 0.3                       # FPFH 法向量估计半径，应满足：fpfh_radius >= 1.5 * fpfh_normal_radius
      fpfh_radius: 0.5                              # FPFH 特征计算半径，应满足：fpfh_radius >= 1.5 * fpfh_normal_radius
      estimating_scale: false                       # 是否同时估计尺度，激光点云刚体配准通常设为 false
      noise_bound: 0.1                             # 测量噪声上界，通常建议设置在 v/2 ~ v 之间（v 为体素分辨率）
      rotation:
        num_max_iter: 50                            # 旋转估计最大迭代次数，通常小于 20 次即可收敛
        gnc_factor: 1.4                             # 控制非线性增强速度，值越大，非线性增强越快
        rot_cost_diff_threshold: 0.0001             # 相邻两次迭代的代价函数差值阈值，小于该值则认为旋转优化收敛
        # 当连续两次迭代的代价差小于该阈值时，旋转优化结束